# Generated by Django 2.2.9 on 2020-05-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_newpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
